# Generated by Django 6.0.7 on 2026-09-23 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('excavator', 'Excavator'), ('bulldozer', 'Bulldozer'), ('loader', 'Wheel Loader'), ('grader', 'Motor Grader'), ('crane', 'Crane'), ('dumper', 'Dump Truck'), ('tractor', 'Tractor'), ('generator', 'Generator'), ('compressor', 'Compressor'), ('forklift', 'Forklift'), ('other', 'Other')], max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('current_hours', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service'), ('retired', 'Retired')], default='active', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='companies.site')),
            ],
            options={
                'ordering': ['asset_number'],
                'constraints': [models.UniqueConstraint(fields=('company', 'asset_number'), name='unique_asset_number_per_company')],
            },
        ),
    ]
