# Generated by Django 4.1 on 2026-09-25 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('A', 'A Service'), ('A2', 'A2 Service'), ('B', 'B Service'), ('C', 'C Service'), ('D', 'D Service'), ('OTHER', 'Other')], max_length=20)),
                ('hour_meter_at_service', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('service_interval', models.DecimalField(decimal_places=1, default=250, max_digits=12)),
                ('next_service', models.DecimalField(decimal_places=1, editable=False, max_digits=12)),
                ('air_filter_status', models.CharField(choices=[('not_due', 'Not Due'), ('service', 'Service')], default='not_due', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_records', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
    ]
