# Generated by Django 4.1 on 2026-09-25 21:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options_alter_site_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('previous_reading', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=1, max_digits=12)),
                ('hours_worked', models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=12)),
                ('reading_type', models.CharField(choices=[('daily', 'Daily Reading'), ('weekly', 'Weekly Reading'), ('monthly', 'Monthly Reading'), ('service', 'Service Reading'), ('initial', 'Initial Reading'), ('correction', 'Correction')], default='daily', max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_meter_readings', to='equipment.equipment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_hour_meter_readings', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_meter_readings', to='companies.site')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hour_meter_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hourmeterreading',
            index=models.Index(fields=['equipment', 'reading_date'], name='hourmeter_h_equipme_fe8548_idx'),
        ),
        migrations.AddIndex(
            model_name='hourmeterreading',
            index=models.Index(fields=['site', 'reading_date'], name='hourmeter_h_site_id_16b685_idx'),
        ),
    ]
